@startuml AddOpening
left to right direction
skinparam monochrome false
skinparam shadowing false

actor "Користувач" as user

rectangle "3.6 Додати вікно/двері на стіну" {

  usecase "3.6 Створити отвір" as UC367
  usecase "3.6.1 Вибрати стіну для додавання отвору" as UC361
  usecase "3.6.2 Вибрати тип отвору" as UC362
  usecase "3.6.3 Задати геометрію отвору" as UC363
  usecase "3.6.5 Вибрати матеріал" as UC365
  usecase "3.6.6 Виправити невірні значення" as UC366
  usecase "3.6.8 Оновити план та теплову модель" as UC368
}

user --> UC367

UC367 ..> UC361 : <<include>>
UC367 ..> UC362 : <<include>>
UC367 ..> UC363 : <<include>>
UC367 ..> UC365 : <<include>>
UC367 ..> UC368 : <<include>>

UC363 ..> UC366 : <<extend>>

@enduml
